[services]
lutris = True
gog = True
egs = True
origin = False
ubisoft = True
steam = True
xdg = False
steamwindows = False
humblebundle = True
ea_app = False
battlenet = False
itchio = False

[lutris]
library_ignores = 
migration_version = 14
show_advanced_options = True
show_hidden_games = true
hide_client_on_game_start = True
dark_theme = True
view_type = grid
pga_cache_path = /home/daniel/.cache/lutris/installer
filter_installed = False
width = 1830
height = 1014
window_x = 2937
window_y = 1086
maximized = False
selected_category = category:all
icon_type_gridview_steam = banner
show_tray_icon = True
icon_type_gridview = coverart_big
view_sorting = name
view_sorting_ascending = True
view_sorting_installed_first = True
icon_type_listview = coverart_med
icon_type_gridview_ubisoft = cover
hide_badges_on_icons = True
icon_type_gridview_egs = game_banner_small
icon_type_gridview_xdg = icon
icon_type_gridview_gog = banner
icon_type_gridview_humblebundle = big_icon
icon_type_gridview_origin = packArtSmall
icon_type_gridview_itchio = banner
hide_text_under_icons = False

[list view]
name_column_width = 200
year_column_width = 60
runner_column_width = 120
platform_column_width = 120
lastplayed_column_width = 238
installedat_column_width = 120
playtime_column_width = 100

