#!/bin/sh

USER_RESOURCES="${XDG_CONFIG_HOME}/x11/Xresources"
USER_MODMAP="${XDG_CONFIG_HOME}/x11/Xmodmap"
SYS_RESOURCES="/etc/X11/xinit/.Xresources"
SYS_MODMAP="/etc/X11/xinit/.Xmodmap"

[ -f "${SYS_RESOURCES}"  ] && xrdb -merge "${SYS_RESOURCES}"
[ -f "${USER_RESOURCES}" ] && xrdb -merge "${USER_RESOURCES}"
[ -f "${SYS_MODMAP}"     ] && xmodmap "${SYS_MODMAP}"
[ -f "${USER_MODMAP}"    ] && xmodmap "${USER_MODMAP}"

run () {
    if ! pgrep "${1}" ; then
        printf "Running %s\n" "${@}"
        "${@}" > "${XDG_CACHE_HOME}/logs/${1}.log" 2>&1 &
    fi
}

printf -- "\n---------- Setting up X config... ----------\n"

DP_MONITORS=$(xrandr | grep -v "eDP1" | grep "DP" | grep -e "\bconnected\b"),
HDMI_MONITORS=$(xrandr | grep "HDMI" | grep -e "\bconnected\b")
if [ -n "${DP_MONITORS}" ] ; then
    source "${XDG_CONFIG_HOME}/arandr/2_monitors_dp.sh"
elif [ -n "${HDMI_MONITORS}" ] ; then
    source "${XDG_CONFIG_HOME}/arandr/2_monitors_hdmi.sh"
else
    source "${XDG_CONFIG_HOME}/arandr/laptop_monitor.sh"
fi

# run xrandr --output HDMI1 --rotate left  2>/dev/null
# run xlayoutdisplay --dpi 96 --wait 3

printf "Done.\n"
printf -- "\n---------- Starting applications... ----------\n"
run keyboard-center
run openrgb --startminimized --profile "G910"

sleep 5;

printf -- "\n---------- Starting window manager desktop environment... ----------\n"

run lxsession -s "Awesome" -e "Awesome"
run dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
awesome --replace > "${XDG_CACHE_HOME}/logs/awesomewm.log" 2>&1
