mappings:
  MEMORY_1:
    MACRO_1:
      gamemode: 0
      name: ''
      string: '`'
      type: key
      value: [1, 41]
    MACRO_2:
      gamemode: 0
      name: ''
      string: Tab
      type: key
      value: [1, 15]
    MACRO_3:
      gamemode: 0
      name: ''
      string: '0x37'
      type: key
      value: [1, 29]
    MACRO_4:
      gamemode: 0
      name: ''
      string: '0x50'
      type: key
      value: [1, 42]
    MACRO_5:
      gamemode: 0
      name: ''
      string: '0x37'
      type: key
      value: [1, 29]
    MACRO_8:
      gamemode: 0
      name: Screen Off
      string: '0x253'
      type: key
      value: [1, 245]
    MACRO_9:
      gamemode: 0
      name: Sleep
      string: Sleep
      type: key
      value: [1, 142]
  MEMORY_3:
    MACRO_9:
      gamemode: 0
      name: Restart OpenRGB
      string: command
      type: command
      value: [5, /bin/sh -c "killall openrgb; sleep 2s; openrgb --profile "G910" --startminimized"]
openRGB: {MEMORY_1: G910, MEMORY_2: G910, MEMORY_3: G910}
settings: {minOnStart: true, retryCount: 5, showNotifications: false, usbDeviceID: 0,
  usbTimeout: 1000, useOpenRGB: true}
